# ALS Signal source import template (pipe-delimited)
#
# Purpose: This file records the Source details shown for sources that are
# initially disabled in the app. It is deliberately suitable for a future
# import function. The first non-comment line is the header row; each later
# line is one source. Do not change the header names without updating the
# future importer.
#
# Adding a source: locate the publisher's official RSS or Atom feed URL. Open
# that URL in a browser or feed reader and confirm it returns RSS/Atom XML,
# rather than an ordinary HTML page. Read the publisher's linked Terms, RSS
# policy, copyright notice, and reuse/licensing information. Record the exact
# terms URL and any rights contact. If no RSS-specific permission is stated,
# use the conservative values shown below: headline, date, attribution, and
# outbound link only; permission and commercial use are not verified.
#
# File structure: comments may be placed before the schema and must start with
# '#'. The first non-comment line is the schema/header. Every subsequent
# non-comment line is data. Blank lines are ignored. Do not add a second header.
# Validate the complete file before importing it; an invalid row must not be
# partially imported.
#
# Field expectations:
# source_id: required stable identifier; letters, numbers, '-' and '_' only.
# name: required display name for the source.
# endpoint: required absolute HTTP or HTTPS RSS/Atom URL.
# category: exactly News, Research, or Community. This value determines the
# app's internal category; do not use All.
# feed_kind: one of direct, complete, alsFiltered, headlineOnly, yahoo, google.
# The app enforces this value at import and after restart. headlineOnly and
# google feeds are used only for relevance filtering and display headline,
# publication date, source attribution, and outbound link; their summaries
# are discarded before display. alsFiltered and yahoo feeds are relevance
# filtered. Use complete only when the publisher's terms support feed summaries.
# enabled_by_default: exactly true or false. Use false unless reviewed.
# publisher: publisher's display/legal name as shown in Source details.
# classification: e.g. Open or public data, Licensed source, Headline-only
# source, Intermediary, Permission under review, or User-provided feed.
# reviewed: date the terms were checked, preferably 'DD Month YYYY'.
# fields_displayed: concise description of the fields the app displays.
# permission: specific permission statement, or explain that it is unverified.
# commercial_use: commercial-use restriction or 'Not verified.'.
# attribution: required publisher attribution and original-link instruction.
# terms_url: absolute HTTP/HTTPS terms or RSS-policy URL; blank if unavailable.
# rights_or_corrections_contact: email or other rights contact; blank if none.
# notes: operational limitations, verification caveats, and storage/display notes.
#
# Values are pipe-delimited. If a value itself contains a pipe, replace it
# with \|; replace line breaks with a space. The reviewed date is the date the
# terms were checked, not a guarantee that the publisher's terms remain
# unchanged. The user remains responsible for review.
#
source_id|name|endpoint|category|feed_kind|enabled_by_default|publisher|classification|reviewed|fields_displayed|permission|commercial_use|attribution|terms_url|rights_or_corrections_contact|notes
yahoo-health|Yahoo News · Health|https://news.yahoo.com/rss/health|News|yahoo|false|Yahoo News|Licensed source|24 July 2026|Feed title, summary, publication date, attribution and outbound link|Yahoo Terms of Service section 15 permits display of content supplied in a Yahoo RSS Feed, subject to its conditions.|Feed advertising is prohibited; the app contains no advertising.|Attribute the named publisher and link to the original page.|https://legal.yahoo.com/xw/en/yahoo/terms/otos/index.html||Preserve publisher attribution and link to the original page. Do not reproduce full articles or publisher images.
london-standard|The London Standard · News|https://www.standard.co.uk/news/rss|News|headlineOnly|false|Evening Standard Limited · The London Standard|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|Use remains subject to the publisher’s feed terms.|Headline-and-link use only; broader content reuse requires publisher authorization.|Attribute the named publisher and link to the original page.|https://www.standard.co.uk/service/terms-of-use-6902768.html|syndication@standard.co.uk|Optional and off by default. The feed summary is used transiently for ALS/MND relevance filtering, then discarded. No summary, image or article body is stored or displayed.
sciencedaily-als|ScienceDaily · ALS|https://www.sciencedaily.com/rss/health_medicine/amyotrophic_lateral_sclerosis.xml|Research|complete|false|ScienceDaily LLC|Licensed source|24 July 2026|Feed title, summary, publication date, attribution and outbound link|ScienceDaily expressly permits its RSS feeds for commercial and noncommercial organizations, subject to its RSS Terms of Use.|Permitted without a feed-content fee; advertising associated with RSS content is prohibited.|Attribute the named publisher and link to the original page.|https://www.sciencedaily.com/terms.htm||Optional and off by default. Full articles and publisher images are not reproduced.
mda-quest|MDA Quest|https://mdaquest.org/feed/|Community|headlineOnly|false|Muscular Dystrophy Association · Quest|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|MDA terms require prior written permission for reproduction or third-party redistribution. This source is restricted to headline, date, attribution and outbound link until authorization is obtained.|Not permitted under the reviewed standard terms without written authorization.|Attribute the named publisher and link to the original page.|https://www.mda.org/terms-of-use||Optional and off by default. Headline-only display is used pending written permission; no summary, image or article body is stored or displayed.
all-als|ALL ALS Consortium|https://www.all-als.org/feed/|Research|headlineOnly|false|Access for All in ALS Consortium|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|ALL ALS grants personal-use access but prohibits automated harvesting and copying without authorization. This source is restricted to headline, date, attribution and outbound link.|Not permitted under the reviewed standard terms without written authorization.|Attribute the named publisher and link to the original page.|https://www.all-als.org/general-terms-of-service/||Optional and off by default. Automated reuse is restricted by the reviewed terms; no summary, image or article body is stored or displayed.
als-canada|ALS Society of Canada|https://als.ca/feed/|Community|headlineOnly|false|ALS Society of Canada|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|No RSS-specific reuse permission was verified. Keep this source to headline, date, attribution and outbound link pending confirmation.|Not verified.|Attribute the named publisher and link to the original page.|https://als.ca/terms-of-use/||Optional and off by default. No RSS-specific reuse permission was verified; no summary, image or article body is stored or displayed.
les-turner-als|Les Turner ALS Foundation|https://lesturnerals.org/feed/|Research|headlineOnly|false|Les Turner ALS Foundation|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|No RSS-specific reuse permission was verified. Keep this source to headline, date, attribution and outbound link pending confirmation.|Not verified.|Attribute the named publisher and link to the original page.|||Optional and off by default. No RSS-specific reuse permission was verified; no summary, image or article body is stored or displayed.
johns-hopkins-hub|Johns Hopkins · Research Hub|https://hub.jhu.edu/feed/|Research|alsFiltered|false|Johns Hopkins University · Hub|Open or public data|24 July 2026|Feed title, summary, publication date, NIH attribution and outbound link|Johns Hopkins provides this institutional research feed, but no reuse permission was verified. Display headline, date, attribution and outbound link pending authorization.|Not verified.|Attribute the named publisher and link to the original page.|https://pages.jh.edu/news_info/news/rss/||Optional and off by default. The broad institutional feed is filtered locally for ALS/MND relevance. No summary, image or article body is stored or displayed.
rnz-world|RNZ · World News|https://www.rnz.co.nz/rss/world.xml|News|headlineOnly|false|Radio New Zealand · World|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|RNZ publishes this public World RSS feed for personal use only. Redistribution requires express permission; this source is restricted to headline, date, attribution and outbound link.|Not permitted for redistribution without express permission.|Attribute the named publisher and link to the original page.|https://www.rnz.co.nz/rss||Optional and off by default. RNZ requires express permission for redistribution; only headline, date, attribution and outbound link are shown.
fight-mnd|FightMND · Australia|https://fightmnd.org.au/feed/|Community|headlineOnly|false|FightMND Australia|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|No RSS-specific reuse permission was verified. Keep this source to headline, date, attribution and outbound link pending confirmation.|Not verified.|Attribute the named publisher and link to the original page.|https://fightmnd.org.au/news/||Optional and off by default. International source; RSS-specific reuse permission was not independently verified. No summary, image or article body is stored or displayed.
mnd-australia|MND Australia|https://www.mndaustralia.org.au/feed/|Community|headlineOnly|false|MND Australia|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|No RSS-specific reuse permission was verified. Keep this source to headline, date, attribution and outbound link pending confirmation.|Not verified.|Attribute the named publisher and link to the original page.|https://www.mndaustralia.org.au/articles/media-releases||Optional and off by default. International source; RSS-specific reuse permission was not independently verified. No summary, image or article body is stored or displayed.
imnda-ireland|Irish MND Association|https://www.imnda.ie/feed|Community|headlineOnly|false|Irish Motor Neurone Disease Association|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|No RSS-specific reuse permission was verified. Keep this source to headline, date, attribution and outbound link pending confirmation.|Not verified.|Attribute the named publisher and link to the original page.|https://www.imnda.ie/blog||Optional and off by default. International source; RSS-specific reuse permission was not independently verified. No summary, image or article body is stored or displayed.
als-mnd-alliance|International ALS/MND Alliance|https://www.als-mnd.org/feed/|Research|headlineOnly|false|International Alliance of ALS/MND Associations|Headline-only source|24 July 2026|Exact headline, publication date, source name and outbound article URL only|No RSS-specific reuse permission was verified. Keep this source to headline, date, attribution and outbound link pending confirmation.|Not verified.|Attribute the named publisher and link to the original page.|https://www.als-mnd.org/||Optional and off by default. International source; RSS-specific reuse permission was not independently verified. No summary, image or article body is stored or displayed.
google-news|Google News · ALS & MND|https://news.google.com/rss/search?q=%28ALS%20OR%20%22amyotrophic%20lateral%20sclerosis%22%20OR%20%22motor%20neurone%20disease%22%29&hl=en-GB&gl=GB&ceid=GB:en|News|google|false|Google News|Intermediary|24 July 2026|Feed title, summary, publication date, attribution and outbound link|Permission has not been recorded. Keep this source disabled unless authorized.|Not verified.|Attribute the named publisher and link to the original page.|||Not approved for release use. Keep disabled unless Google and relevant publishers provide authorization.
reuters|Reuters coverage via Google News|https://news.google.com/rss/search?q=%28ALS%20OR%20%22amyotrophic%20lateral%20sclerosis%22%29%20source%3AReuters&hl=en-GB&gl=GB&ceid=GB:en|News|google|false|Reuters coverage via Google News|Intermediary|24 July 2026|Feed title, summary, publication date, attribution and outbound link|Permission has not been recorded. Keep this source disabled unless authorized.|Not verified.|Attribute the named publisher and link to the original page.|||Not approved for release use. Keep disabled unless Google and relevant publishers provide authorization.
alstdi|ALS TDI via Google News|https://news.google.com/rss/search?q=%28ALS%20OR%20%22amyotrophic%20lateral%20sclerosis%22%29%20site%3Aals.net&hl=en-GB&gl=GB&ceid=GB:en|Research|google|false|ALS Therapy Development Institute via Google News|Intermediary|24 July 2026|Feed title, summary, publication date, attribution and outbound link|Permission has not been recorded. Keep this source disabled unless authorized.|Not verified.|Attribute the named publisher and link to the original page.|||Not approved for release use. Keep disabled unless Google and relevant publishers provide authorization.
alsa|ALS Association via Google News|https://news.google.com/rss/search?q=%28ALS%20OR%20%22amyotrophic%20lateral%20sclerosis%22%29%20site%3Aals.org&hl=en-GB&gl=GB&ceid=GB:en|Community|google|false|The ALS Association via Google News|Intermediary|24 July 2026|Feed title, summary, publication date, attribution and outbound link|Permission has not been recorded. Keep this source disabled unless authorized.|Not verified.|Attribute the named publisher and link to the original page.|||Not approved for release use. Keep disabled unless Google and relevant publishers provide authorization.
mnd-association|MND Association via Google News|https://news.google.com/rss/search?q=%28MND%20OR%20%22motor%20neurone%20disease%22%29%20site%3Amndassociation.org&hl=en-GB&gl=GB&ceid=GB:en|Community|google|false|MND Association via Google News|Intermediary|24 July 2026|Feed title, summary, publication date, attribution and outbound link|Permission has not been recorded. Keep this source disabled unless authorized.|Not verified.|Attribute the named publisher and link to the original page.|||Not approved for release use. Keep disabled unless Google and relevant publishers provide authorization.
